### ISSUE TITLE
Video frames are ignored due to type mismatch

### ISSUE THREAD

**Issue by sullvn** [aurora-opensource/xviz#569]
I'm seeing video frames being ignored due to a type mismatch. `Blob` is used to check for video messages [in the latest code](https://github.com/uber/xviz/blob/master/modules/parser/src/parsers/parse-xviz-message-sync.js#L35) while `ArrayBuffer` is what I'm actually encountering:

```js
  // here, not all arraybuffer may be image (packed point cloud)
  if (typeof Blob !== 'undefined' && message instanceof Blob) {
    parseVideoMessageV1(message, onResult, onError);
    return;
  }
```

This modified version works:

```js
  if (typeof ArrayBuffer !== 'undefined' && message instanceof ArrayBuffer) {
    parseVideoMessageV1(message, onResult, onError);
    return;
  }
```

I'm making an issue instead of a PR because that comment above hints there may be a regression by just changing to `ArrayBuffer`. There isn't other information available -- besides trying to decode it -- to do an intelligent detection of video frames. So I'm not sure what the best course of action is.

Here's that comment again:

```js
  // here, not all arraybuffer may be image (packed point cloud)
```

**Comment by twojtasz** [comment]
clearly need a better test case for this, however V1 will be removed soon (it was only an internal thing as no open source V1 builders exist).
