### ISSUE TITLE
Time-series support for object ID's is not functional

### ISSUE THREAD

**Issue by twojtasz** [aurora-opensource/xviz#648]
The builder will create them, but when parsing it complains about `Unexpected time_series duplicate`.

It looks like parsing does not consider the object_id at all and reports the duplicate.  And looking at Streetscape.gl it has little to no handling for this either.

**Comment by shreyas2311** [comment]
I am trying to have two time series data in the same graph, for example a reference and actual velocity. Is this issue referring to the same as well?

**Comment by twojtasz** [comment]
@shreyas2311 The issue i'm referring to is at the data parsing level.  This has been fixed but i'll look at what it would take to have 2 time-series values in the same graph.  I recall we supported this as it is very common to want targer vs measured metrics.

**Comment by shreyas2311** [comment]
@twojtasz Yes. I got this to work. This is not an issue. Thanks.
