### ISSUE TITLE
the polylines drawing error

### ISSUE THREAD

**Issue by liyongyang** [aurora-opensource/xviz#672]
When drawing the path of the vehicle, there is a strange broken line at the end point
like this:
![image](https://user-images.githubusercontent.com/38446040/141773858-215e33e3-865a-4a88-a1a3-f76ad54dd997.png)
polylines:
[
  [
    815.02,
    -645.41,
    0
  ],
  [
    812.75,
    -645.49,
    0
  ],
  [
    810.4,
    -645.68,
    0
  ],
  [
    808.17,
    -645.96,
    0
  ],
  [
    806.28,
    -646.24,
    0
  ],
  [
    804.22,
    -646.58,
    0
  ],
  [
    802,
    -646.96,
    0
  ],
  [
    799.66,
    -647.36,
    0
  ],
  [
    797.3,
    -647.75,
    0
  ],
  [
    794.93,
    -648.13,
    0
  ],
  [
    792.56,
    -648.5,
    0
  ],
  [
    790.19,
    -648.87,
    0
  ],
  [
    787.82,
    -649.23,
    0
  ],
  [
    785.44,
    -649.6,
    0
  ],
  [
    783.06,
    -649.97,
    0
  ]
]

**Comment by vvvvjvvvv** [comment]
same issue here 
i may lose my jobs if this problem remains

**Comment by twojtasz** [comment]
Using the playground (https://avs.auto/playground/) I don't see the issue.  What version of deck.gl do you have? @liyongyang iyongyang

**Comment by twojtasz** [comment]
Cannot reproduce.
