### ISSUE TITLE
Kitti example is not running

### ISSUE THREAD

**Issue by azamshoaib** [aurora-opensource/xviz#679]
@twojtasz Hi, thank you for this awesome project. I am running the kitti demo. I have followed the instructions but unfortunately I am getting the error as shown in the figure below

![image](https://user-images.githubusercontent.com/16619808/149351548-13cc85ea-d5e0-477c-9f40-876752115f85.png)

Kindly help me in this regard. Thank you

**Comment by SlahserZ** [comment]
FYI, hope this helps.
https://github.com/uber/streetscape.gl/issues/523

**Comment by azamshoaib** [comment]
@SlahserZ Thank you. I will give it a try and let see if it resolves the issue.

**Comment by lesun90** [comment]
The problem comes from the new update of loaders.gl package. Follow this fix for the temporary fix.

https://github.com/aurora-opensource/xviz/issues/663

**Comment by twojtasz** [comment]
@xviz 1.0.11 fixes this, i'm publish streetscape.gl updates too.
